### ISSUE TITLE
bug in the readme

### ISSUE THREAD

**Issue by GrosSacASac** [knpwrs/babel-plugin-remove-bugs#3]
babel-plugin-remove-bugs can! With this plugin enabled, Babel will output the following: 

and then comes nothing

**Comment by knpwrs** [comment]
Try it out. The output is accurate.

**Comment by GrosSacASac** [comment]
still nothing, readme.md line 61

https://github.com/knpwrs/babel-plugin-remove-bugs/blame/master/README.md#L61
